/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPost200Response{}

// UserPost200Response struct for UserPost200Response
type UserPost200Response struct {
	Id *int `json:"id,omitempty"`
}

// NewUserPost200Response instantiates a new UserPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPost200Response() *UserPost200Response {
	this := UserPost200Response{}
	return &this
}

// NewUserPost200ResponseWithDefaults instantiates a new UserPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPost200ResponseWithDefaults() *UserPost200Response {
	this := UserPost200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserPost200Response) GetId() int {
	if o == nil || IsNil(o.Id) {
		var ret int
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPost200Response) GetIdOk() (*int, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserPost200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int and assigns it to the Id field.
func (o *UserPost200Response) SetId(v int) {
	o.Id = &v
}

func (o UserPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableUserPost200Response struct {
	value *UserPost200Response
	isSet bool
}

func (v NullableUserPost200Response) Get() *UserPost200Response {
	return v.value
}

func (v *NullableUserPost200Response) Set(val *UserPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPost200Response(val *UserPost200Response) *NullableUserPost200Response {
	return &NullableUserPost200Response{value: val, isSet: true}
}

func (v NullableUserPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


