/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TweetsTweetIdPut500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TweetsTweetIdPut500Response{}

// TweetsTweetIdPut500Response struct for TweetsTweetIdPut500Response
type TweetsTweetIdPut500Response struct {
	Message *string `json:"message,omitempty"`
}

// NewTweetsTweetIdPut500Response instantiates a new TweetsTweetIdPut500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetsTweetIdPut500Response() *TweetsTweetIdPut500Response {
	this := TweetsTweetIdPut500Response{}
	return &this
}

// NewTweetsTweetIdPut500ResponseWithDefaults instantiates a new TweetsTweetIdPut500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetsTweetIdPut500ResponseWithDefaults() *TweetsTweetIdPut500Response {
	this := TweetsTweetIdPut500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TweetsTweetIdPut500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetsTweetIdPut500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TweetsTweetIdPut500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TweetsTweetIdPut500Response) SetMessage(v string) {
	o.Message = &v
}

func (o TweetsTweetIdPut500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TweetsTweetIdPut500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableTweetsTweetIdPut500Response struct {
	value *TweetsTweetIdPut500Response
	isSet bool
}

func (v NullableTweetsTweetIdPut500Response) Get() *TweetsTweetIdPut500Response {
	return v.value
}

func (v *NullableTweetsTweetIdPut500Response) Set(val *TweetsTweetIdPut500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetsTweetIdPut500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetsTweetIdPut500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetsTweetIdPut500Response(val *TweetsTweetIdPut500Response) *NullableTweetsTweetIdPut500Response {
	return &NullableTweetsTweetIdPut500Response{value: val, isSet: true}
}

func (v NullableTweetsTweetIdPut500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetsTweetIdPut500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


