/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserGet401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGet401Response{}

// UserGet401Response struct for UserGet401Response
type UserGet401Response struct {
	Message *string `json:"message,omitempty"`
}

// NewUserGet401Response instantiates a new UserGet401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGet401Response() *UserGet401Response {
	this := UserGet401Response{}
	return &this
}

// NewUserGet401ResponseWithDefaults instantiates a new UserGet401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGet401ResponseWithDefaults() *UserGet401Response {
	this := UserGet401Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UserGet401Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGet401Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UserGet401Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UserGet401Response) SetMessage(v string) {
	o.Message = &v
}

func (o UserGet401Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGet401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUserGet401Response struct {
	value *UserGet401Response
	isSet bool
}

func (v NullableUserGet401Response) Get() *UserGet401Response {
	return v.value
}

func (v *NullableUserGet401Response) Set(val *UserGet401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGet401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGet401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGet401Response(val *UserGet401Response) *NullableUserGet401Response {
	return &NullableUserGet401Response{value: val, isSet: true}
}

func (v NullableUserGet401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGet401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


