/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SigninPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SigninPostRequest{}

// SigninPostRequest struct for SigninPostRequest
type SigninPostRequest struct {
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewSigninPostRequest instantiates a new SigninPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSigninPostRequest() *SigninPostRequest {
	this := SigninPostRequest{}
	return &this
}

// NewSigninPostRequestWithDefaults instantiates a new SigninPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSigninPostRequestWithDefaults() *SigninPostRequest {
	this := SigninPostRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SigninPostRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigninPostRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SigninPostRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SigninPostRequest) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *SigninPostRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SigninPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *SigninPostRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *SigninPostRequest) SetPassword(v string) {
	o.Password = &v
}

func (o SigninPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SigninPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableSigninPostRequest struct {
	value *SigninPostRequest
	isSet bool
}

func (v NullableSigninPostRequest) Get() *SigninPostRequest {
	return v.value
}

func (v *NullableSigninPostRequest) Set(val *SigninPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSigninPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSigninPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSigninPostRequest(val *SigninPostRequest) *NullableSigninPostRequest {
	return &NullableSigninPostRequest{value: val, isSet: true}
}

func (v NullableSigninPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSigninPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


