/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPostRequest{}

// UserPostRequest struct for UserPostRequest
type UserPostRequest struct {
	DisplayName string `json:"display_name"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type _UserPostRequest UserPostRequest

// NewUserPostRequest instantiates a new UserPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPostRequest(displayName string, username string, password string) *UserPostRequest {
	this := UserPostRequest{}
	this.DisplayName = displayName
	this.Username = username
	this.Password = password
	return &this
}

// NewUserPostRequestWithDefaults instantiates a new UserPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPostRequestWithDefaults() *UserPostRequest {
	this := UserPostRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *UserPostRequest) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *UserPostRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *UserPostRequest) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetUsername returns the Username field value
func (o *UserPostRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserPostRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserPostRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *UserPostRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserPostRequest) SetPassword(v string) {
	o.Password = v
}

func (o UserPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["display_name"] = o.DisplayName
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *UserPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"display_name",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserPostRequest := _UserPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserPostRequest)

	if err != nil {
		return err
	}

	*o = UserPostRequest(varUserPostRequest)

	return err
}

type NullableUserPostRequest struct {
	value *UserPostRequest
	isSet bool
}

func (v NullableUserPostRequest) Get() *UserPostRequest {
	return v.value
}

func (v *NullableUserPostRequest) Set(val *UserPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPostRequest(val *UserPostRequest) *NullableUserPostRequest {
	return &NullableUserPostRequest{value: val, isSet: true}
}

func (v NullableUserPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


