/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HelloGet500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloGet500Response{}

// HelloGet500Response struct for HelloGet500Response
type HelloGet500Response struct {
	Message *string `json:"message,omitempty"`
}

// NewHelloGet500Response instantiates a new HelloGet500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloGet500Response() *HelloGet500Response {
	this := HelloGet500Response{}
	return &this
}

// NewHelloGet500ResponseWithDefaults instantiates a new HelloGet500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloGet500ResponseWithDefaults() *HelloGet500Response {
	this := HelloGet500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *HelloGet500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelloGet500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *HelloGet500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *HelloGet500Response) SetMessage(v string) {
	o.Message = &v
}

func (o HelloGet500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloGet500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableHelloGet500Response struct {
	value *HelloGet500Response
	isSet bool
}

func (v NullableHelloGet500Response) Get() *HelloGet500Response {
	return v.value
}

func (v *NullableHelloGet500Response) Set(val *HelloGet500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloGet500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloGet500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloGet500Response(val *HelloGet500Response) *NullableHelloGet500Response {
	return &NullableHelloGet500Response{value: val, isSet: true}
}

func (v NullableHelloGet500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloGet500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


