/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommentsCommentIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommentsCommentIdPutRequest{}

// CommentsCommentIdPutRequest struct for CommentsCommentIdPutRequest
type CommentsCommentIdPutRequest struct {
	Body string `json:"body"`
}

type _CommentsCommentIdPutRequest CommentsCommentIdPutRequest

// NewCommentsCommentIdPutRequest instantiates a new CommentsCommentIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommentsCommentIdPutRequest(body string) *CommentsCommentIdPutRequest {
	this := CommentsCommentIdPutRequest{}
	this.Body = body
	return &this
}

// NewCommentsCommentIdPutRequestWithDefaults instantiates a new CommentsCommentIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentsCommentIdPutRequestWithDefaults() *CommentsCommentIdPutRequest {
	this := CommentsCommentIdPutRequest{}
	return &this
}

// GetBody returns the Body field value
func (o *CommentsCommentIdPutRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *CommentsCommentIdPutRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *CommentsCommentIdPutRequest) SetBody(v string) {
	o.Body = v
}

func (o CommentsCommentIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommentsCommentIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

func (o *CommentsCommentIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommentsCommentIdPutRequest := _CommentsCommentIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommentsCommentIdPutRequest)

	if err != nil {
		return err
	}

	*o = CommentsCommentIdPutRequest(varCommentsCommentIdPutRequest)

	return err
}

type NullableCommentsCommentIdPutRequest struct {
	value *CommentsCommentIdPutRequest
	isSet bool
}

func (v NullableCommentsCommentIdPutRequest) Get() *CommentsCommentIdPutRequest {
	return v.value
}

func (v *NullableCommentsCommentIdPutRequest) Set(val *CommentsCommentIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentsCommentIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentsCommentIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentsCommentIdPutRequest(val *CommentsCommentIdPutRequest) *NullableCommentsCommentIdPutRequest {
	return &NullableCommentsCommentIdPutRequest{value: val, isSet: true}
}

func (v NullableCommentsCommentIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentsCommentIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


