/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Error500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Error500Response{}

// Error500Response struct for Error500Response
type Error500Response struct {
	Message *string `json:"message,omitempty"`
}

// NewError500Response instantiates a new Error500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewError500Response() *Error500Response {
	this := Error500Response{}
	return &this
}

// NewError500ResponseWithDefaults instantiates a new Error500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewError500ResponseWithDefaults() *Error500Response {
	this := Error500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Error500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Error500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Error500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Error500Response) SetMessage(v string) {
	o.Message = &v
}

func (o Error500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Error500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableError500Response struct {
	value *Error500Response
	isSet bool
}

func (v NullableError500Response) Get() *Error500Response {
	return v.value
}

func (v *NullableError500Response) Set(val *Error500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableError500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableError500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableError500Response(val *Error500Response) *NullableError500Response {
	return &NullableError500Response{value: val, isSet: true}
}

func (v NullableError500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableError500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


