/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TweetsTweetIdPut204Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TweetsTweetIdPut204Response{}

// TweetsTweetIdPut204Response struct for TweetsTweetIdPut204Response
type TweetsTweetIdPut204Response struct {
	Id *int `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewTweetsTweetIdPut204Response instantiates a new TweetsTweetIdPut204Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetsTweetIdPut204Response() *TweetsTweetIdPut204Response {
	this := TweetsTweetIdPut204Response{}
	return &this
}

// NewTweetsTweetIdPut204ResponseWithDefaults instantiates a new TweetsTweetIdPut204Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetsTweetIdPut204ResponseWithDefaults() *TweetsTweetIdPut204Response {
	this := TweetsTweetIdPut204Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TweetsTweetIdPut204Response) GetId() int {
	if o == nil || IsNil(o.Id) {
		var ret int
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetsTweetIdPut204Response) GetIdOk() (*int, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TweetsTweetIdPut204Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int and assigns it to the Id field.
func (o *TweetsTweetIdPut204Response) SetId(v int) {
	o.Id = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *TweetsTweetIdPut204Response) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TweetsTweetIdPut204Response) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *TweetsTweetIdPut204Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *TweetsTweetIdPut204Response) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o TweetsTweetIdPut204Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TweetsTweetIdPut204Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableTweetsTweetIdPut204Response struct {
	value *TweetsTweetIdPut204Response
	isSet bool
}

func (v NullableTweetsTweetIdPut204Response) Get() *TweetsTweetIdPut204Response {
	return v.value
}

func (v *NullableTweetsTweetIdPut204Response) Set(val *TweetsTweetIdPut204Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetsTweetIdPut204Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetsTweetIdPut204Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetsTweetIdPut204Response(val *TweetsTweetIdPut204Response) *NullableTweetsTweetIdPut204Response {
	return &NullableTweetsTweetIdPut204Response{value: val, isSet: true}
}

func (v NullableTweetsTweetIdPut204Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetsTweetIdPut204Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


