/*
Twitter API

This is a sample server Twitter API server.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TweetsTweetIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TweetsTweetIdPutRequest{}

// TweetsTweetIdPutRequest struct for TweetsTweetIdPutRequest
type TweetsTweetIdPutRequest struct {
	Title string `json:"title"`
	Body string `json:"body"`
}

type _TweetsTweetIdPutRequest TweetsTweetIdPutRequest

// NewTweetsTweetIdPutRequest instantiates a new TweetsTweetIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTweetsTweetIdPutRequest(title string, body string) *TweetsTweetIdPutRequest {
	this := TweetsTweetIdPutRequest{}
	this.Title = title
	this.Body = body
	return &this
}

// NewTweetsTweetIdPutRequestWithDefaults instantiates a new TweetsTweetIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTweetsTweetIdPutRequestWithDefaults() *TweetsTweetIdPutRequest {
	this := TweetsTweetIdPutRequest{}
	return &this
}

// GetTitle returns the Title field value
func (o *TweetsTweetIdPutRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TweetsTweetIdPutRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TweetsTweetIdPutRequest) SetTitle(v string) {
	o.Title = v
}

// GetBody returns the Body field value
func (o *TweetsTweetIdPutRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *TweetsTweetIdPutRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *TweetsTweetIdPutRequest) SetBody(v string) {
	o.Body = v
}

func (o TweetsTweetIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TweetsTweetIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

func (o *TweetsTweetIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTweetsTweetIdPutRequest := _TweetsTweetIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTweetsTweetIdPutRequest)

	if err != nil {
		return err
	}

	*o = TweetsTweetIdPutRequest(varTweetsTweetIdPutRequest)

	return err
}

type NullableTweetsTweetIdPutRequest struct {
	value *TweetsTweetIdPutRequest
	isSet bool
}

func (v NullableTweetsTweetIdPutRequest) Get() *TweetsTweetIdPutRequest {
	return v.value
}

func (v *NullableTweetsTweetIdPutRequest) Set(val *TweetsTweetIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTweetsTweetIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTweetsTweetIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTweetsTweetIdPutRequest(val *TweetsTweetIdPutRequest) *NullableTweetsTweetIdPutRequest {
	return &NullableTweetsTweetIdPutRequest{value: val, isSet: true}
}

func (v NullableTweetsTweetIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTweetsTweetIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


